import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: ['class'],
  content: ['./src/**/*.{ts,tsx}', './app/**/*.{ts,tsx}', './components/**/*.{ts,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        body: ['var(--font-body)', 'sans-serif'],
        heading: ['var(--font-heading)', 'sans-serif'],
        sora: ['var(--font-heading)', 'Sora', 'sans-serif'],
        'be-vietnam': ['var(--font-body)', 'Be Vietnam Pro', 'sans-serif'],
      },
      colors: {
        primary: {
          50: '#fff4ed',
          100: '#ffe6d5',
          200: '#fecba8',
          300: '#fda86b',
          400: '#fb8c3a',
          500: '#f97316',
          600: '#ea580c',
          700: '#c2410c',
          800: '#9a3412',
          900: '#7c2d12',
        },
        'flash-sale': '#ff2d2d',
        gold: '#f59e0b',
        // Material Design 3 color tokens for auth pages
        'm3-primary': '#0035d1',
        'm3-on-primary': '#ffffff',
        'm3-primary-container': '#1e4cfd',
        'm3-on-primary-container': '#dbdeff',
        'm3-secondary': '#4958a9',
        'm3-on-secondary': '#ffffff',
        'm3-secondary-container': '#9aa8ff',
        'm3-tertiary': '#3432c8',
        'm3-on-tertiary': '#ffffff',
        'm3-tertiary-container': '#4e4fe0',
        'm3-error': '#ba1a1a',
        'm3-on-error': '#ffffff',
        'm3-surface': '#fcf8ff',
        'm3-on-surface': '#08006c',
        'm3-on-surface-variant': '#444656',
        'm3-surface-variant': '#e1dfff',
        'm3-surface-container': '#eeecff',
        'm3-surface-container-low': '#f5f2ff',
        'm3-surface-container-high': '#e8e6ff',
        'm3-surface-container-highest': '#e1dfff',
        'm3-surface-container-lowest': '#ffffff',
        'm3-outline': '#747688',
        'm3-outline-variant': '#c4c5d9',
        'm3-on-background': '#08006c',
        'm3-primary-fixed': '#dee1ff',
        'm3-tertiary-fixed': '#e1dfff',
        'm3-secondary-fixed': '#dee0ff',
        'm3-inverse-primary': '#bac3ff',
        'm3-inverse-surface': '#1401a8',
        'm3-inverse-on-surface': '#f2efff',
      },
      spacing: {
        'gutter': '1.5rem',
        'section-gap': '4rem',
      },
      animation: {
        shimmer: 'shimmer 1.5s infinite',
        'fade-in': 'fadeIn 0.3s ease',
        'slide-up': 'slideUp 0.3s ease',
        'countdown-flip': 'flip 0.5s ease',
        'float': 'float 6s ease-in-out infinite',
      },
      keyframes: {
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        fadeIn: {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
        slideUp: {
          from: { opacity: '0', transform: 'translateY(10px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        flip: {
          '0%': { transform: 'rotateX(0)' },
          '50%': { transform: 'rotateX(-90deg)' },
          '100%': { transform: 'rotateX(0)' },
        },
        float: {
          '0%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-20px)' },
          '100%': { transform: 'translateY(0px)' },
        },
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
}
export default config
