import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "#2e2bc3",
        "on-surface-variant": "#444656",
        "on-secondary": "#ffffff",
        "on-secondary-fixed-variant": "#303f90",
        "background": "#fcf8ff",
        "on-primary": "#ffffff",
        "on-background": "#08006c",
        "primary": "#0035d1",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#4e4fe0",
        "secondary-fixed": "#dee0ff",
        "primary-container": "#1e4cfd",
        "error": "#ba1a1a",
        "outline": "#747688",
        "on-primary-fixed-variant": "#0031c5",
        "primary-fixed-dim": "#bac3ff",
        "on-primary-fixed": "#001159",
        "surface-dim": "#d8d6ff",
        "secondary-container": "#9aa8ff",
        "surface-tint": "#1246f8",
        "surface-variant": "#e1dfff",
        "tertiary-fixed-dim": "#c1c1ff",
        "on-error-container": "#93000a",
        "surface-container-low": "#f5f2ff",
        "on-tertiary-fixed": "#08006c",
        "surface": "#fcf8ff",
        "outline-variant": "#c4c5d9",
        "on-secondary-fixed": "#00105a",
        "secondary": "#4958a9",
        "inverse-on-surface": "#f2efff",
        "on-secondary-container": "#2a3a8a",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#dee1ff",
        "secondary-fixed-dim": "#bac3ff",
        "inverse-surface": "#1401a8",
        "surface-container-highest": "#e1dfff",
        "tertiary": "#3432c8",
        "on-tertiary-container": "#dfdeff",
        "on-primary-container": "#dbdeff",
        "surface-container": "#eeecff",
        "on-error": "#ffffff",
        "surface-container-high": "#e8e6ff",
        "surface-bright": "#fcf8ff",
        "error-container": "#ffdad6",
        "tertiary-fixed": "#e1dfff",
        "on-surface": "#08006c",
        "inverse-primary": "#bac3ff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "16px",
        "3xl": "32px",
        full: "9999px",
      },
      spacing: {
        "stack-lg": "1.5rem",
        "section-gap": "4rem",
        "stack-sm": "0.5rem",
        "stack-md": "1rem",
        gutter: "1.5rem",
        "margin-mobile": "1rem",
        "container-max": "1280px",
      },
      fontFamily: {
        "body-md": ["var(--font-body)", "Be Vietnam Pro", "sans-serif"],
        caption: ["var(--font-body)", "Be Vietnam Pro", "sans-serif"],
        "display-lg": ["var(--font-heading)", "Sora", "sans-serif"],
        "price-display": ["var(--font-body)", "Be Vietnam Pro", "sans-serif"],
        "headline-lg": ["var(--font-heading)", "Sora", "sans-serif"],
        "headline-sm": ["var(--font-heading)", "Sora", "sans-serif"],
        "headline-md": ["var(--font-heading)", "Sora", "sans-serif"],
        "body-lg": ["var(--font-body)", "Be Vietnam Pro", "sans-serif"],
        "label-md": ["var(--font-body)", "Be Vietnam Pro", "sans-serif"],
        "display-lg-mobile": ["var(--font-heading)", "Sora", "sans-serif"],
        sora: ["var(--font-heading)", "Sora", "sans-serif"],
        body: ["var(--font-body)", "Be Vietnam Pro", "sans-serif"],
        heading: ["var(--font-heading)", "Sora", "sans-serif"],
        "be-vietnam": ["var(--font-body)", "Be Vietnam Pro", "sans-serif"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        caption: ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "800" }],
        "price-display": ["20px", { lineHeight: "1", fontWeight: "700" }],
        "headline-lg": ["30px", { lineHeight: "40px", fontWeight: "700" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "display-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "800" }],
      },
      animation: {
        shimmer: "shimmer 1.5s infinite",
        "fade-in": "fadeIn 0.3s ease",
        "slide-up": "slideUp 0.3s ease",
        "countdown-flip": "flip 0.5s ease",
        float: "float 6s ease-in-out infinite",
      },
      keyframes: {
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
        fadeIn: {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
        slideUp: {
          from: { opacity: "0", transform: "translateY(10px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        flip: {
          "0%": { transform: "rotateX(0)" },
          "50%": { transform: "rotateX(-90deg)" },
          "100%": { transform: "rotateX(0)" },
        },
        float: {
          "0%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-20px)" },
          "100%": { transform: "translateY(0px)" },
        },
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
export default config;
