import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#f8fafc",
        "on-background": "#191c1e",
        surface: "#f7f9fb",
        "surface-page": "#f8fafc",
        "surface-dim": "#d8dadc",
        "surface-bright": "#f7f9fb",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f4f6",
        "surface-container": "#eceef0",
        "surface-container-high": "#e6e8ea",
        "surface-container-highest": "#e0e3e5",
        "on-surface": "#191c1e",
        "on-surface-variant": "#584237",
        "inverse-surface": "#2d3133",
        "inverse-on-surface": "#eff1f3",
        outline: "#8c7164",
        "outline-variant": "#e0c0b1",
        "surface-tint": "#9d4300",
        primary: "#9d4300",
        "on-primary": "#ffffff",
        "primary-container": "#f97316",
        "on-primary-container": "#582200",
        "inverse-primary": "#ffb690",
        secondary: "#a73a00",
        "on-secondary": "#ffffff",
        "secondary-container": "#fd651e",
        "on-secondary-container": "#571a00",
        tertiary: "#855300",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#d78900",
        "on-tertiary-container": "#492c00",
        error: "#ef4444",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#ffdbca",
        "primary-fixed-dim": "#ffb690",
        "on-primary-fixed": "#341100",
        "on-primary-fixed-variant": "#783200",
        "secondary-fixed": "#ffdbce",
        "secondary-fixed-dim": "#ffb599",
        "on-secondary-fixed": "#370e00",
        "on-secondary-fixed-variant": "#7f2b00",
        "tertiary-fixed": "#ffddb8",
        "tertiary-fixed-dim": "#ffb95f",
        "on-tertiary-fixed": "#2a1700",
        "on-tertiary-fixed-variant": "#653e00",
        "surface-variant": "#e0e3e5",
        "primary-50": "#fff4ed",
        "primary-500": "#f97316",
        "primary-600": "#ea580c",
        "primary-900": "#7c2d12",
        "brand-orange": "#f97316",
        "flash-sale": "#ff2d2d",
        gold: "#f59e0b",
        success: "#22c55e",
        "border-subtle": "#f1f5f9",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        sm: "0.25rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "0.75rem",
        "2xl": "16px",
        "3xl": "32px",
        full: "9999px",
      },
      spacing: {
        "stack-lg": "1.5rem",
        "section-gap": "2.5rem",
        "stack-sm": "0.5rem",
        "stack-md": "1rem",
        gutter: "1rem",
        "margin-mobile": "1rem",
        "container-max": "1280px",
      },
      fontFamily: {
        "body-md": ["var(--font-body)", "Be Vietnam Pro", "sans-serif"],
        caption: ["var(--font-body)", "Be Vietnam Pro", "sans-serif"],
        "display-lg": ["var(--font-heading)", "Sora", "sans-serif"],
        "display-sm": ["var(--font-heading)", "Sora", "sans-serif"],
        "price-display": ["var(--font-heading)", "Sora", "sans-serif"],
        "price-xl": ["var(--font-heading)", "Sora", "sans-serif"],
        "headline-lg": ["var(--font-heading)", "Sora", "sans-serif"],
        "headline-sm": ["var(--font-heading)", "Sora", "sans-serif"],
        "headline-md": ["var(--font-heading)", "Sora", "sans-serif"],
        "body-lg": ["var(--font-body)", "Be Vietnam Pro", "sans-serif"],
        "label-md": ["var(--font-body)", "Be Vietnam Pro", "sans-serif"],
        "display-lg-mobile": ["var(--font-heading)", "Sora", "sans-serif"],
        sora: ["var(--font-heading)", "Sora", "sans-serif"],
        body: ["var(--font-body)", "Be Vietnam Pro", "sans-serif"],
        heading: ["var(--font-heading)", "Sora", "sans-serif"],
        "be-vietnam": ["var(--font-body)", "Be Vietnam Pro", "sans-serif"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        caption: ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "display-sm": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "price-display": ["30px", { lineHeight: "36px", fontWeight: "700" }],
        "price-xl": ["30px", { lineHeight: "36px", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "16px", fontWeight: "600", letterSpacing: "0.01em" }],
        "display-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
      },
      boxShadow: {
        "primary-glow": "0 10px 15px -3px rgba(249, 115, 22, 0.3)",
        card: "0 1px 3px 0 rgba(0, 0, 0, 0.05)",
        "card-hover": "0 10px 15px -3px rgba(0, 0, 0, 0.1)",
      },
      animation: {
        shimmer: "shimmer 1.5s infinite",
        "fade-in": "fadeIn 0.3s ease",
        "slide-up": "slideUp 0.3s ease",
        "countdown-flip": "flip 0.5s ease",
        float: "float 6s ease-in-out infinite",
      },
      keyframes: {
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
        fadeIn: {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
        slideUp: {
          from: { opacity: "0", transform: "translateY(10px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        flip: {
          "0%": { transform: "rotateX(0)" },
          "50%": { transform: "rotateX(-90deg)" },
          "100%": { transform: "rotateX(0)" },
        },
        float: {
          "0%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-20px)" },
          "100%": { transform: "translateY(0px)" },
        },
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
export default config;
